# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Title (display)
title: Japan Dynamics CRM & Power Platform Support Blog
# Sub Title (display)
subtitle: 日本マイクロソフトの Dynamics CRM & Power Platform テクニカル サポート チームより、情報をお届けします！
# Description
description: 日本マイクロソフトの Dynamics CRM & Power Platform テクニカル サポート チームより、情報をお届けします！

# Keywords
keywords:
  - Power Apps
  - Power Automate
  - PPAC
  - Power Apps Portal
  - モデル駆動型 アプリ
  - キャンバス アプリ

author: Japan Dynamics CRM & Power Platform Support Team

# Tag (hexo helper)
root_tag_generator:
  root_tag_names:
    - Information
    - Archive
    - Governance
    - How to
    - Connector and Connection
    - Microsoft Teams 連携
    - Network
    - License
    - お問い合わせ全般
    - 重要な変更点 (廃止)
    - Power Apps
    - Power Automate
    - Power Automate for desktop
    - Microsoft Copilot Studio
    - Power Pages
    - Power Platform
    - Dynamics
    - Dynamics 365
    - Dataverse
    - Model-driven app
    - PowerShell
  sub_tag_limit: 0

root_cat_generator:
  root_cat_names:
    - [サポートサービスのご利用について]
    - [Power Apps]
    - [Power Apps, Canvas app]
    - [Power Apps, Model-driven app]
    - [Power Automate]
    - [Power Automate, Cloud flow]
    - [Power Automate, Desktop flow]
    - [Dynamics 365]
    - [Power Pages]
    - [Power Platform Admin Center]
    - [Dataverse]
    - [Microsoft Copilot Studio]
    - [AI Builder]

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://jpdynamicscrm.github.io/blog/
github:
#  2025/02/27 kosukehara 更新履歴とコントリビューター表示追加対応　
  url: https://github.com/jpdynamicscrm/blog/
  posts_dir: articles
#  default_branch: ma
#  2025/02/19 kosukehara 更新履歴とコントリビューターを取得して表示
#  url: https://github.com/jpazureid/blog/
#  posts_dir: articles
#  default_branch: main
  show_additional_info: true


skip_render:
  - '_data/*.png'
  # Bing Webmaster
  - 'BingSiteAuth.xml'
  # Search Console
  - 'google471f926fb901d82b.html'

# Deployment
## Docs: https://hexo.io/doc  s/deployment.html
deploy:
  type: git
  repo: git@github.com:jpdynamicscrm/blog.git
  branch: gh-pages
  message: "Site updated: {{ now('YYYY-MM-DD HH:mm:ss') }} [skip ci]"

root: /blog/
permalink: :title/
permalink_defaults: 

language: ja
timezone: asia/Tokyo

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
# pagination
archive: 2

new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: true
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 0
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: jpazure

feed:
  type: atom
  path: atom.xml
  limit: 20

  # show disclaimer in all article by default. disableDisclaimer of article's option set true hide.
# ex) 
# ---
# title: Article Title
# date: 2020-04-30 10:00
# disableDisclaimer: true
# ---
disclaimer: ※本情報の内容（添付文書、リンク先などを含む）は、作成日時点でのものであり、予告なく変更される場合があります。